---
# tasks file for httpd
- include_vars: ../vars/main.yml
- name: Install httpd
  yum:
    name: httpd
    state: present
- name: start and enable httpd
  service:
    name: httpd
    state: started
    enabled: true
- name: configure firewalld
  ansible.posix.firewalld:
    service: '{{ item }}'
    permanent: true
    state: enabled
  with_items: '{{ web }}'
- name: restart firewalld
  service:
    name: firewalld
    state: reloaded

